{{- include "stig-manager.validateValues" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stig-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stig-manager.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stig-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- /* Roll the pods when the rendered config or secret changes. */}}
        checksum/config: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        {{- if include "stig-manager.createSecret" . }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if include "stig-manager.createCAConfigMap" . }}
        checksum/ca: {{ include (print $.Template.BasePath "/configmap-ca.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "stig-manager.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stig-manager.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "stig-manager.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ include "stig-manager.containerPort" . }}
              protocol: TCP
            {{- with .Values.extraContainerPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "stig-manager.configMapName" . }}
            {{- range .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- $env := include "stig-manager.env" . | trim }}
          {{- if or $env .Values.extraEnvVars }}
          env:
            {{- with $env }}
            {{- . | nindent 12 }}
            {{- end }}
            {{- with .Values.extraEnvVars }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- if .Values.startupProbe.custom }}
            {{- toYaml .Values.startupProbe.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
              scheme: {{ include "stig-manager.probeScheme" . }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- if .Values.readinessProbe.custom }}
            {{- toYaml .Values.readinessProbe.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
              scheme: {{ include "stig-manager.probeScheme" . }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- if .Values.livenessProbe.custom }}
            {{- toYaml .Values.livenessProbe.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
              scheme: {{ include "stig-manager.probeScheme" . }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            {{- end }}
          {{- end }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.tmpVolume.enabled }}
            - name: tmp
              mountPath: /tmp
            {{- end }}
            {{- if include "stig-manager.caEnabled" . }}
            - name: ca-bundle
              mountPath: {{ .Values.trustedCAs.mountPath }}
              readOnly: true
            {{- end }}
            {{- if .Values.database.tls.enabled }}
            - name: db-tls
              mountPath: {{ .Values.database.tls.mountPath }}
              readOnly: true
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: api-tls
              mountPath: {{ .Values.tls.mountPath }}
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
        {{- with .Values.sidecars }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.tmpVolume.enabled }}
        - name: tmp
          emptyDir:
            medium: {{ .Values.tmpVolume.medium | quote }}
            {{- with .Values.tmpVolume.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
        {{- end }}
        {{- if include "stig-manager.caEnabled" . }}
        - name: ca-bundle
          {{- if .Values.trustedCAs.existingSecret }}
          secret:
            secretName: {{ .Values.trustedCAs.existingSecret }}
            defaultMode: 0444
          {{- else }}
          configMap:
            name: {{ include "stig-manager.caConfigMapName" . }}
            defaultMode: 0444
          {{- end }}
        {{- end }}
        {{- if .Values.database.tls.enabled }}
        - name: db-tls
          secret:
            secretName: {{ .Values.database.tls.existingSecret }}
            defaultMode: 0400
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: api-tls
          secret:
            secretName: {{ .Values.tls.existingSecret }}
            defaultMode: 0400
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
