{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "stig-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stig-manager.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "stig-manager.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.allowAllIngress }}
    - ports:
        - port: {{ include "stig-manager.containerPort" . }}
          protocol: TCP
    {{- else }}
    - from:
        {{- with .Values.networkPolicy.allowedIngress }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      ports:
        - port: {{ include "stig-manager.containerPort" . }}
          protocol: TCP
        {{- with .Values.networkPolicy.extraIngressPorts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.allowAllEgress }}
    - {}
    {{- else }}
    {{- if .Values.networkPolicy.egress.dns }}
    # DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.egress.database }}
    {{- if .enabled }}
    # External MySQL
    - to:
        {{- if .to }}
        {{- tpl (toYaml .to) $ | nindent 8 }}
        {{- else }}
        - ipBlock:
            cidr: 0.0.0.0/0
        {{- end }}
      ports:
        - port: {{ .port | default $.Values.database.port | default 3306 }}
          protocol: TCP
    {{- end }}
    {{- end }}
    {{- with .Values.networkPolicy.egress.extra }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- end }}
{{- end }}
