{{- if include "stig-manager.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stig-manager.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stig-manager.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.database.password }}
  {{ $.Values.database.secretKeys.password }}: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.database.tls.keyPassphrase }}
  {{ $.Values.database.secretKeys.dbTlsKeyPassphrase }}: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.tls.keyPassphrase }}
  {{ $.Values.database.secretKeys.apiTlsKeyPassphrase }}: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
